name: wheelmap
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  http: ^0.13.6
  flutter_native_splash: ^2.2.0+1
  ionicons: ^0.2.2
  sliding_up_panel: ^2.0.0+1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.0.3
  logger: ^1.4.0
  fl_chart: ^0.63.0
  go_router: ^9.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.1

flutter_native_splash:
  color: "#FFBF00"
  color_dark: "#ffe7a1"
  android: true
  image: assets/images/Logo-black.png
  image_dark: assets/images/Logo-black.png
  fullscreen: true
  android_12:
    color: "#FFBF00"
    color_dark: "#ffe7a1"
    image: assets/images/splash-logo.png
    image_dark: assets/images/splash-logo.png
    fullscreen: true


flutter_app_name:
  name: "WheelMap"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/surfaces/
    - assets/json/routes.json
    - assets/json/accessibility_data.json
    - .env
