// These values are from open route service and can be view at https://giscience.github.io/openrouteservice/documentation/extra-info/Surface.html
const appSurfacesImages = {
  0: 'assets/surfaces/unknown.png',
  1: 'assets/surfaces/paved.png',
  2: 'assets/surfaces/unpaved.png',
  3: 'assets/surfaces/asphalt.png',
  4: 'assets/surfaces/concrete.png',
  5: 'assets/surfaces/cobblestone.png',
  6: 'assets/surfaces/metal.png',
  7: 'assets/surfaces/wood.png',
  8: 'assets/surfaces/compacted_gravel.png',
  9: 'assets/surfaces/fine_gravel.png',
  10: 'assets/surfaces/gravel.png',
  11: 'assets/surfaces/dirt.png',
  12: 'assets/surfaces/ground.png',
  13: 'assets/surfaces/ice.png',
  14: 'assets/surfaces/paving_stones.png',
  15: 'assets/surfaces/sand.png',
  16: 'assets/surfaces/woodchips.png',
  17: 'assets/surfaces/grass.png',
  18: 'assets/surfaces/grass_paver.png',
};

const appSurfacesNames = {
  0: 'Unknown',
  1: 'Paved',
  2: 'Unpaved',
  3: 'Asphalt',
  4: 'Concrete',
  5: 'Cobblestone',
  6: 'Metal',
  7: 'Wood',
  8: 'Compacted Gravel',
  9: 'Fine Gravel',
  10: 'Gravel',
  11: 'Dirt',
  12: 'Ground',
  13: 'Ice',
  14: 'Paving Stones',
  15: 'Sand',
  16: 'Woodchips',
  17: 'Grass',
  18: 'Grass Paver',
};